apiVersion: v1
kind: Pod
metadata:
  name: sample-app
spec:
  containers:
  - name: sample-app
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: tmp-volume
      mountPath: "/tmp"
      readOnly: false
  volumes:
  - name: tmp-volume
    emptyDir:
      sizeLimit: 10Mi
