apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restrictive-psp-role
  namespace: with-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
