---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  selector:
    app: sample-app
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: cve-2017-5638-sample-non-root
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
