---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  ports:
  - name: http
    nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  containers:
  - name: sample-app
    image: jrrdev/cve-2017-5638:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
