apiVersion: v1
kind: Pod
metadata:
  name: sample-app
spec:
  automountServiceAccountToken: false
  containers:
  - name: sample-app
    securityContext:
      runAsUser: 1111
      runAsNonRoot: true
      allowPrivilegeEscalation: false
